version: '3'

services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  db:
    build:
      context: .
      dockerfile: DockerfilePost
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: MarlBoro-001
#    volumes:
#      - ./data:/var/lib/postgresql/data
