version: '3'

services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: MarlBoro-001
    volumes:
      - ./data:/var/lib/postgresql/data
    command: "pg_restore -d ./MarlBoro-001 -U postgres -C MarlBoro-001.sql"

