version: '3'

services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - db
    restart: always

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: MarlBoro-001
    volumes:
      - ./data:/var/lib/postgresql/data

